export interface LanguageConfig {
  id: string;
  name: string;
  nativeName: string;
  region: "Pan-India" | "North" | "South" | "East" | "West" | "North-East" | "Central" | "Classical" | "Global";
  speechCode: string;
  slogan: string;
  greeting: string;
  samplePrompt: string;
}

export const ALL_LANGUAGES: LanguageConfig[] = [
  // Pan-India / Common
  {
    id: "en",
    name: "English",
    nativeName: "English",
    region: "Pan-India",
    speechCode: "en-IN",
    slogan: "Don't Just Know the Weather. Know What to Do.",
    greeting: "Hello!",
    samplePrompt: "Should I take an umbrella today?",
  },
  {
    id: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    region: "Pan-India",
    speechCode: "hi-IN",
    slogan: "मौसम सिर्फ जानिए नहीं — उसके हिसाब से फैसला लीजिए।",
    greeting: "नमस्ते!",
    samplePrompt: "क्या आज बारिश होगी? क्या मैं बाइक से जा सकता हूँ?",
  },
  {
    id: "hinglish",
    name: "Hinglish",
    nativeName: "Hinglish (हिंग्लिश)",
    region: "Pan-India",
    speechCode: "hi-IN",
    slogan: "Mausam sirf jaaniye nahi — uske hisaab se faisla lijiye!",
    greeting: "Namaste!",
    samplePrompt: "Kya aaj umbrella le jana chahiye? Shaam ko safe hai nikalna?",
  },

  // 22 Official Eighth Schedule Indian Languages
  {
    id: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    region: "East",
    speechCode: "bn-IN",
    slogan: "শুধু আবহাওয়া জানবেন না — সঠিক সিদ্ধান্ত নিন।",
    greeting: "নমস্কার!",
    samplePrompt: "আজ কি বৃষ্টি হবে? বাইরে যাওয়ার জন্য কি সতর্কতা দরকার?",
  },
  {
    id: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    region: "West",
    speechCode: "mr-IN",
    slogan: "केवळ हवामान समजू नका — त्यानुसार निर्णय घ्या.",
    greeting: "नमस्कार!",
    samplePrompt: "आज पाऊस पडेल का? बाईकने प्रवास करणे सुरक्षित आहे का?",
  },
  {
    id: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    region: "South",
    speechCode: "te-IN",
    slogan: "వాతావరణాన్ని తెలుసుకోవడమే కాదు — సరైన నిర్ణయం తీసుకోండి.",
    greeting: "నమస్కారం!",
    samplePrompt: "ఈ రోజు వర్షం పడుతుందా? నేను ప్రయాణం చేయవచ్చా?",
  },
  {
    id: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    region: "South",
    speechCode: "ta-IN",
    slogan: "வானிலை அறிக்கை மட்டுமல்ல — அதற்கான முடிவுகளையும் எடுங்கள்.",
    greeting: "வணக்கம்!",
    samplePrompt: "இன்று மழை பெய்யுமா? குடை எடுத்துச் செல்ல வேண்டுமா?",
  },
  {
    id: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    region: "West",
    speechCode: "gu-IN",
    slogan: "માત્ર હવામાન જાણો નહીં — તેના આધારે નિર્ણય લો.",
    greeting: "નમસ્તે!",
    samplePrompt: "શું આજે વરસાદ પડશે? છત્રી લઈ જવાની જરૂર છે?",
  },
  {
    id: "ur",
    name: "Urdu",
    nativeName: "اردو",
    region: "Pan-India",
    speechCode: "ur-IN",
    slogan: "صرف موسم کا حال نہ جانیں — اس کے مطابق فیصلہ کریں۔",
    greeting: "آداب!",
    samplePrompt: "کیا آج بارش ہونے کا امکان ہے؟ سفر کے لیے کیا احتیاط ہے؟",
  },
  {
    id: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    region: "South",
    speechCode: "kn-IN",
    slogan: "ಹವಾಮಾನವನ್ನು ಕೇವಲ ತಿಳಿಯಬೇಡಿ — ಅದಕ್ಕೆ ತಕ್ಕ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಿ.",
    greeting: "ನಮಸ್ಕಾರ!",
    samplePrompt: "ಇಂದು ಮಳೆ ಬರುತ್ತದೆಯೇ? ಹೊರಗೆ ಹೋಗುವುದು ಸುರಕ್ಷಿತವೇ?",
  },
  {
    id: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
    region: "East",
    speechCode: "or-IN",
    slogan: "କେବଳ ପାଣିପାଗ ଜାଣନ୍ତୁ ନାହିଁ — ତାହା ଅନୁଯାୟୀ ନିଷ୍ପତ୍ତି ନିଅନ୍ତୁ।",
    greeting: "ନମସ୍କାର!",
    samplePrompt: "ଆଜି କ’ଣ ବର୍ଷା ହେବ? ଛତା ନେବା ଆବଶ୍ୟକ କି?",
  },
  {
    id: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    region: "South",
    speechCode: "ml-IN",
    slogan: "കാലാവസ്ഥ അറിയുക മാത്രമല്ല — അതിനനുസരിച്ച് തീരുമാനം എടുക്കുക.",
    greeting: "നമസ്കാരം!",
    samplePrompt: "ഇന്ന് മഴ പെയ്യുമോ? യാത്ര സുരക്ഷിതമാണോ?",
  },
  {
    id: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    region: "North",
    speechCode: "pa-IN",
    slogan: "ਸਿਰਫ਼ ਮੌਸਮ ਜਾਣੋ ਨਾ — ਉਸ ਦੇ ਮੁਤਾਬਕ ਫ਼ੈਸਲਾ ਲਵੋ।",
    greeting: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ!",
    samplePrompt: "ਕੀ ਅੱਜ ਮੀਂਹ ਪਵੇਗਾ? ਕੀ ਛਤਰੀ ਲਿਜਾਣੀ ਚਾਹੀਦੀ ਹੈ?",
  },
  {
    id: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    region: "North-East",
    speechCode: "as-IN",
    slogan: "কেৱল বতৰৰ খবৰ নহয় — তাৰ ভিত্তিত সিদ্ধান্ত লওক।",
    greeting: "নমস্কাৰ!",
    samplePrompt: "আজি বৰষুণ হ'ব নেকি? যাত্ৰাৰ বাবে কি সাৱধানতা ল'ব লাগিব?",
  },
  {
    id: "mai",
    name: "Maithili",
    nativeName: "मैथिली",
    region: "East",
    speechCode: "hi-IN",
    slogan: "मौसम सिर्फ नहि जानी — ओहि अनुसार निर्णय लिअ।",
    greeting: "प्रणाम!",
    samplePrompt: "की आइज बरखा होयत? बहार जेबा लेल की सावधानी चाही?",
  },
  {
    id: "sat",
    name: "Santali",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ (Santali)",
    region: "East",
    speechCode: "hi-IN",
    slogan: "ᱫᱟᱜᱼᱡᱟᱹᱲᱤ ᱵᱟᱰᱟᱭ ᱥᱩᱢᱩᱝ ᱵᱟᱝ — ᱚᱱᱟ ᱞᱮᱠᱟᱛᱮ ᱩᱭᱦᱟᱹᱨ ᱢᱮ᱾",
    greeting: "ᱡᱚᱦᱟᱨ!",
    samplePrompt: "ᱛᱮᱦᱮᱧ ᱪᱮᱫ ᱫᱟᱜ ᱦᱤᱡᱩᱜᱼᱟ? ᱪᱷᱟᱛᱟ ᱤᱫᱤ ᱞᱟᱹᱠᱛᱤ ᱢᱮᱱᱟᱜᱼᱟ?",
  },
  {
    id: "ks",
    name: "Kashmiri",
    nativeName: "کٲشُر / कॉशुर",
    region: "North",
    speechCode: "ks-IN",
    slogan: "موسم صِرف زانِو نَہ — تَمِہ مُطٲبِق کٔرِو فٲصلہٕ۔",
    greeting: "سلام!",
    samplePrompt: "کیاہ اَز پؠیہِ رُود یا شِین؟ کیاہ تَدَابِیر چھِ ضَرورِی؟",
  },
  {
    id: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    region: "North",
    speechCode: "ne-NP",
    slogan: "मौसम मात्र नजान्नुहोस् — त्यस अनुसार निर्णय लिनुहोस्।",
    greeting: "नमस्ते!",
    samplePrompt: "के आज पानी पर्छ? यात्रा गर्न सुरक्षित छ?",
  },
  {
    id: "kok",
    name: "Konkani",
    nativeName: "कोंकणी",
    region: "West",
    speechCode: "kok-IN",
    slogan: "फकत हवामान समजू नका — ताच्या प्रमाण निर्णय घ्या.",
    greeting: "नमस्कार!",
    samplePrompt: "आयज पावस पडटलो काय? भायर वचपाक काय सावधताय घेवची?",
  },
  {
    id: "sd",
    name: "Sindhi",
    nativeName: "سنڌي / सिंधी",
    region: "West",
    speechCode: "sd-IN",
    slogan: "صرف موسم نه ڄاڻو — ان موجب فيصلو ڪيو.",
    greeting: "سلام!",
    samplePrompt: "ڇا اڄ برسات پوندي؟ ڇا ڇٽي کڻڻ ضروري آهي؟",
  },
  {
    id: "doi",
    name: "Dogri",
    nativeName: "डोगरी",
    region: "North",
    speechCode: "doi-IN",
    slogan: "मौसम गी सिर्फ जानो नेईं — उंदे मताबक फैसला लैओ।",
    greeting: "नमस्ते!",
    samplePrompt: "क्या अज्ज मिंह पैग? बाहर जाणे लेई केह् ध्यान रखणा?",
  },
  {
    id: "mni",
    name: "Manipuri",
    nativeName: "ꯃꯤꯇꯩꯂꯣꯟ (Meitei)",
    region: "North-East",
    speechCode: "mni-IN",
    slogan: "নুংশিৎ-নোংগী ফীভম খঙবখক্তা নত্তনা — মদুগী মতুং ইন্না ৱারেপ লৌউ।",
    greeting: "খুরুমজরি!",
    samplePrompt: "ঙসি নোং চুরগদরা? চৎ-থোক তৌবদা করম্বা চেৎশিল্পা চংগনি?",
  },
  {
    id: "brx",
    name: "Bodo",
    nativeName: "बर'",
    region: "North-East",
    speechCode: "as-IN",
    slogan: "अख्रांनि महरखौ मिथिनैल' नङा — बेनि बादियैनो थांखि ला।",
    greeting: "खुलुमबाय!",
    samplePrompt: "दिनै अखा हागोन ना? लामाजों थांनो मोजां जागोन ना?",
  },
  {
    id: "sa",
    name: "Sanskrit",
    nativeName: "संस्कृतम्",
    region: "Classical",
    speechCode: "hi-IN",
    slogan: "केवलं ऋतुज्ञानं न पर्याप्तम् — तदनुरूपं निर्णयं कुरुत।",
    greeting: "नमो नमः!",
    samplePrompt: "अद्य वर्षा भविष्यति किम्? गमनाय का सावधना आवश्यकी?",
  },

  // Global Languages
  {
    id: "es",
    name: "Spanish",
    nativeName: "Español",
    region: "Global",
    speechCode: "es-ES",
    slogan: "No solo conozcas el clima. Sabe qué hacer.",
    greeting: "¡Hola!",
    samplePrompt: "¿Va a llover hoy? ¿Debería llevar paraguas?",
  },
  {
    id: "fr",
    name: "French",
    nativeName: "Français",
    region: "Global",
    speechCode: "fr-FR",
    slogan: "Ne vous contentez pas de connaître la météo. Sachez quoi faire.",
    greeting: "Bonjour!",
    samplePrompt: "Va-t-il pleuvoir aujourd'hui ? Dois-je prendre un parapluie ?",
  },
  {
    id: "de",
    name: "German",
    nativeName: "Deutsch",
    region: "Global",
    speechCode: "de-DE",
    slogan: "Kennen Sie nicht nur das Wetter. Wissen Sie, was zu tun ist.",
    greeting: "Hallo!",
    samplePrompt: "Wird es heute regnen? Sollte ich einen Regenschirm mitnehmen?",
  },
  {
    id: "ar",
    name: "Arabic",
    nativeName: "العربية",
    region: "Global",
    speechCode: "ar-SA",
    slogan: "لا تكتفِ بمعرفة الطقس. اعرف ما يجب عليك فعله.",
    greeting: "مرحباً!",
    samplePrompt: "هل ستمطر اليوم؟ ماذا يجب أن آخذ معي؟",
  },
  {
    id: "ja",
    name: "Japanese",
    nativeName: "日本語",
    region: "Global",
    speechCode: "ja-JP",
    slogan: "天気を知るだけでなく、どう行動すべきかを知ろう。",
    greeting: "こんにちは！",
    samplePrompt: "今日雨は降りますか？傘を持っていくべきですか？",
  },
];

// Helper to look up language config by name or ID
export function getLanguage(nameOrId: string): LanguageConfig {
  const match = ALL_LANGUAGES.find(
    (l) =>
      l.name.toLowerCase() === nameOrId.toLowerCase() ||
      l.id.toLowerCase() === nameOrId.toLowerCase() ||
      l.nativeName.toLowerCase().includes(nameOrId.toLowerCase())
  );
  return match || ALL_LANGUAGES[0]; // defaults to English
}

// BCP-47 speech recognition and speech synthesis locale
export function getSpeechLocale(languageName: string): string {
  const lang = getLanguage(languageName);
  return lang.speechCode || "en-IN";
}

// Key UI translation mappings for primary buttons and section tabs
export interface UITranslationMap {
  missionMode: string;
  radarMap: string;
  emergencySOS: string;
  audioBulletin: string;
  eventSimulator: string;
  citizenPulse: string;
  routeCorridor: string;
  disasterRadar: string;
  sandbox: string;
  weatherDNA: string;
  departure: string;
  askAI: string;
  bagVisionAI: string;
  soundscape: string;
  popular: string;
  gps: string;
  searchPlaceholder: string;
}

const UI_TRANSLATIONS: Record<string, Partial<UITranslationMap>> = {
  English: {
    missionMode: "Weather Mission Mode",
    radarMap: "Live Rain Radar",
    emergencySOS: "Emergency & SOS",
    audioBulletin: "Daily Audio Bulletin",
    eventSimulator: "Event & Wedding Risk",
    citizenPulse: "Citizen Pulse",
    routeCorridor: "Weather Route",
    disasterRadar: "Disaster Radar",
    sandbox: "Weather Simulator",
    weatherDNA: "Weather DNA",
    departure: "5-Min Departure",
    askAI: "Ask VyoomDut AI",
    bagVisionAI: "Bag Vision AI",
    soundscape: "Soundscape",
    popular: "Popular:",
    gps: "GPS",
    searchPlaceholder: "Search any city (e.g., Delhi, Mumbai, Shimla)...",
  },
  Hindi: {
    missionMode: "मौसम मिशन मोड",
    radarMap: "लाइव वर्षा रडार",
    emergencySOS: "आपदा एवं आपातकालीन SOS",
    audioBulletin: "दैनिक मौसम समाचार",
    eventSimulator: "कार्यक्रम व शादी जोखिम",
    citizenPulse: "नागरिक पल्स",
    routeCorridor: "मार्ग कॉरिडोर",
    disasterRadar: "आपदा रडार",
    sandbox: "मौसम सिम्युलेटर",
    weatherDNA: "मौसम डीएनए",
    departure: "प्रस्थान चेकलिस्ट",
    askAI: "पूछें व्योमदूत AI",
    bagVisionAI: "बैग विज़न AI",
    soundscape: "मौसम ध्वनि",
    popular: "प्रमुख शहर:",
    gps: "जीपीएस",
    searchPlaceholder: "शहर खोजें (जैसे दिल्ली, मुंबई, शिमला)...",
  },
  Bengali: {
    missionMode: "আবহাওয়া মিশন মোড",
    radarMap: "লাইভ বৃষ্টি রাডার",
    emergencySOS: "জরুরি এসওএস ও সতর্কতা",
    audioBulletin: "দৈনিক আবহাওয়া বুলেটিন",
    eventSimulator: "অনুষ্ঠান ও বিবাহ ঝুঁকি",
    citizenPulse: "নাগরিক রিপোর্ট",
    routeCorridor: "পথ করিডোর",
    disasterRadar: "দুর্যোগ রাডার",
    sandbox: "আবহাওয়া সিমুলেটর",
    weatherDNA: "ওয়েদার ডিএনএ",
    departure: "যাত্রা চেকলিস্ট",
    askAI: "ব্যোমদূত AI কে জিজ্ঞেস করুন",
    bagVisionAI: "ব্যাগ ভিশন AI",
    soundscape: "আবহাওয়া ধ্বনি",
    popular: "জনপ্রিয় শহর:",
    gps: "জিপিএস",
    searchPlaceholder: "শহর খুঁজুন (যেমন কলকাতা, দিল্লি, দার্জিলিং)...",
  },
  Tamil: {
    missionMode: "வானிலை பணி முறை",
    radarMap: "நேரலை மழை ரேடார்",
    emergencySOS: "அவசர உதவி & SOS",
    audioBulletin: "தினசரி வானிலை செய்தி",
    eventSimulator: "நிகழ்வு & திருமண கணிப்பு",
    citizenPulse: "மக்கள் துடிப்பு",
    routeCorridor: "பாதை தாழ்வாரம்",
    disasterRadar: "பேரிடர் ரேடார்",
    sandbox: "வானிலை சிமுலேட்டர்",
    weatherDNA: "வானிலை டிஎன்ஏ",
    departure: "புறப்பாடு சரிபார்ப்பு",
    askAI: "வியோம்தூத் AI-யிடம் கேளுங்கள்",
    bagVisionAI: "பை பார்வை AI",
    soundscape: "வானிலை ஒலி",
    popular: "முக்கிய நகரங்கள்:",
    gps: "ஜிபிஎஸ்",
    searchPlaceholder: "நகரத்தைத் தேடுங்கள் (எ.கா. சென்னை, மதுரை)...",
  },
  Telugu: {
    missionMode: "వాతావరణ మిషన్ మోడ్",
    radarMap: "లైవ్ వర్షపు రాడార్",
    emergencySOS: "అత్యవసర సహాయం & SOS",
    audioBulletin: "రోజువారీ వాతావరణ బులెటిన్",
    eventSimulator: "ఈవెంట్ & వెడ్డింగ్ రిస్క్",
    citizenPulse: "ప్రజా నివేదికలు",
    routeCorridor: "మార్గం కారిడార్",
    disasterRadar: "విపత్తు రాడార్",
    sandbox: "వాతావరణ సిమ్యులేటర్",
    weatherDNA: "వాతావరణ DNA",
    departure: "బయలుదేరే చెక్‌లిస్ట్",
    askAI: "వ్యోమ్‌దూత్ AI ని అడగండి",
    bagVisionAI: "బ్యాగ్ విజన్ AI",
    soundscape: "వాతావరణ ధ్వని",
    popular: "ప్రముఖ నగరాలు:",
    gps: "జీపీఎస్",
    searchPlaceholder: "నగరాన్ని శోధించండి (ఉదా. హైదరాబాద్, విశాఖ)...",
  },
  Marathi: {
    missionMode: "हवामान मिशन मोड",
    radarMap: "थेट पाऊस रडार",
    emergencySOS: "आपत्कालीन SOS मदत",
    audioBulletin: "दैनिक हवामान बातमीपत्र",
    eventSimulator: "कार्यक्रम व लग्न नियोजन",
    citizenPulse: "नागरिक पल्स",
    routeCorridor: "प्रवास मार्ग",
    disasterRadar: "आपत्ती रडार",
    sandbox: "हवामान सिम्युलेटर",
    weatherDNA: "हवामान डीएनए",
    departure: "प्रस्थान चेकलिस्ट",
    askAI: "व्योमदूत AI ला विचारा",
    bagVisionAI: "बॅग व्हिजन AI",
    soundscape: "हवामान आवाज",
    popular: "प्रमुख शहरे:",
    gps: "जीपीएस",
    searchPlaceholder: "शहर शोधा (उदा. मुंबई, पुणे, नागपूर)...",
  },
  Gujarati: {
    missionMode: "હવામાન મિશન મોડ",
    radarMap: "લાઈવ વરસાદ રડાર",
    emergencySOS: "કટોકટી અને SOS",
    audioBulletin: "દૈનિક હવામાન બુલેટિન",
    citizenPulse: "નાગરિક પલ્સ",
    routeCorridor: "મુસાફરી માર્ગ",
    disasterRadar: "હોનારત રડાર",
    sandbox: "હવામાન સિમ્યુલેટર",
    weatherDNA: "હવામાન ડીએનએ",
    departure: "પ્રસ્થાન ચેકલિસ્ટ",
    askAI: "મૌસમ વાણી AI ને પૂછો",
    bagVisionAI: "બેગ વિઝન AI",
    soundscape: "હવામાન અવાજ",
    popular: "પ્રખ્યાત શહેરો:",
    gps: "જીપીએસ",
    searchPlaceholder: "શહેર શોધો (દા.ત. અમદાવાદ, સુરત, રાજકોટ)...",
  },
  Kannada: {
    missionMode: "ಹವಾಮಾನ ಮಿಷನ್ ಮೋಡ್",
    radarMap: "ಲೈವ್ ಮಳೆ ರಾಡಾರ್",
    emergencySOS: "ತುರ್ತು ನೆರವು & SOS",
    audioBulletin: "ದೈನಂದಿನ ಹವಾಮಾನ ವರದಿ",
    citizenPulse: "ಜನತಾ ವರದಿಗಳು",
    routeCorridor: "ಮಾರ್ಗ ಕಾರಿಡಾರ್",
    disasterRadar: "ವಿಪತ್ತು ರಾಡಾರ್",
    sandbox: "ಹವಾಮಾನ ಸಿಮ್ಯುಲೇಟರ್",
    weatherDNA: "ಹವಾಮಾನ ಡಿಎನ್‌ಎ",
    departure: "ಹೊರಡುವ ಚೆಕ್‌ಲಿಸ್ಟ್",
    askAI: "ಮೌಸಂ ವಾಣಿ AI ಅನ್ನು ಕೇಳಿ",
    bagVisionAI: "ಬ್ಯಾಗ್ ವಿಷನ್ AI",
    soundscape: "ಹವಾಮಾನ ನಾದ",
    popular: "ಪ್ರಮುಖ ನಗರಗಳು:",
    gps: "ಜಿಪಿಎಸ್",
    searchPlaceholder: "ನಗರ ಹುಡುಕಿ (ಉದಾ. ಬೆಂಗಳೂರು, ಮೈಸೂರು)...",
  },
  Malayalam: {
    missionMode: "കാലാവസ്ഥ മിഷൻ മോഡ്",
    radarMap: "തത്സമയ മഴ റഡാർ",
    emergencySOS: "അടിയന്തര സഹായം & SOS",
    audioBulletin: "പ്രതിദിന കാലാവസ്ഥ ബുള്ളറ്റിൻ",
    citizenPulse: "ജനകീയ പൾസ്",
    routeCorridor: "യാത്രാ പാത",
    disasterRadar: "ദുരന്ത റഡാർ",
    sandbox: "കാലാവസ്ഥ സിമുലേറ്റർ",
    weatherDNA: "കാലാവസ്ഥ ഡിഎൻഎ",
    departure: "പുറപ്പെടൽ ചെക്ക്‌ലിസ്റ്റ്",
    askAI: "മൗസം വാണി AI-യോട് ചോദിക്കൂ",
    bagVisionAI: "ബാഗ് വിഷൻ AI",
    soundscape: "കാലാവസ്ഥ ശബ്ദം",
    popular: "പ്രധാന നഗരങ്ങൾ:",
    gps: "ജിപിഎസ്",
    searchPlaceholder: "നഗരം തിരയുക (ഉദാ. കൊച്ചി, തിരുവനന്തപുരം)...",
  },
  Punjabi: {
    missionMode: "ਮੌਸਮ ਮਿਸ਼ਨ ਮੋਡ",
    radarMap: "ਲਾਈਵ ਮੀਂਹ ਰਾਡਾਰ",
    emergencySOS: "ਐਮਰਜੈਂਸੀ ਅਤੇ SOS",
    audioBulletin: "ਰੋਜ਼ਾਨਾ ਮੌਸਮ ਬੁਲੇਟਿਨ",
    citizenPulse: "ਸਿਟੀਜ਼ਨ ਪਲਸ",
    routeCorridor: "ਰੂਟ ਕਾਰੀਡੋਰ",
    disasterRadar: "ਆਫ਼ਤ ਰਾਡਾਰ",
    sandbox: "ਮੌਸਮ ਸਿਮੂਲੇਟਰ",
    weatherDNA: "ਮੌਸਮ ਡੀਐਨਏ",
    departure: "ਰਵਾਨਗੀ ਚੈੱਕਲਿਸਟ",
    askAI: "ਮੌਸਮ ਵਾਣੀ AI ਨੂੰ ਪੁੱਛੋ",
    bagVisionAI: "ਬੈਗ ਵਿਜ਼ਨ AI",
    soundscape: "ਮੌਸਮ ਆਵਾਜ਼",
    popular: "ਪ੍ਰਮੁੱਖ ਸ਼ਹਿਰ:",
    gps: "ਜੀਪੀਐਸ",
    searchPlaceholder: "ਸ਼ਹਿਰ ਲੱਭੋ (ਜਿਵੇਂ ਅੰਮ੍ਰਿਤਸਰ, ਲੁਧਿਆਣਾ)...",
  },
  Odia: {
    missionMode: "ପାଣିପାଗ ମିଶନ ମୋଡ୍",
    radarMap: "ଲାଇଭ ବର୍ଷା ରାଡାର",
    emergencySOS: "ଜରୁରୀକାଳୀନ SOS ସହାୟତା",
    audioBulletin: "ଦୈନିକ ପାଣିପାଗ ସମ୍ବାଦ",
    citizenPulse: "ନାଗରିକ ରିପୋର୍ଟ",
    routeCorridor: "ମାର୍ଗ କରିଡର",
    disasterRadar: "ବିପର୍ଯ୍ୟୟ ରାଡାର",
    sandbox: "ପାଣିପାଗ ସିମୁଲେଟର",
    weatherDNA: "ପାଣିପାଗ DNA",
    departure: "ଯାତ୍ରା ଚେକଲିଷ୍ଟ",
    askAI: "ମୌସମ ବାଣୀ AI କୁ ପଚାରନ୍ତୁ",
    bagVisionAI: "ବ୍ୟାଗ ଭିଜନ AI",
    soundscape: "ପାଣିପାଗ ଧ୍ୱନି",
    popular: "ପ୍ରମୁଖ ସହର:",
    gps: "ଜିପିଏସ",
    searchPlaceholder: "ସହର ଖୋଜନ୍ତୁ (ଯେପରିକି ଭୁବନେଶ୍ୱର, କଟକ)...",
  },
  Assamese: {
    missionMode: "বতৰ মিছন ম'ড",
    radarMap: "লাইভ বৰষুণ ৰাডাৰ",
    emergencySOS: "জৰুৰীকালীন SOS সাহায্য",
    audioBulletin: "দৈনিক বতৰ বুলেটিন",
    citizenPulse: "ৰাইজৰ পালছ",
    routeCorridor: "যাত্ৰা পথ",
    disasterRadar: "দুৰ্যোগ ৰাডাৰ",
    sandbox: "বতৰ চিমুলেটৰ",
    weatherDNA: "বতৰ ডিএনএ",
    departure: "যাত্ৰা পৰীক্ষণ তালিকা",
    askAI: "মৌসম বাণীক সোধক",
    bagVisionAI: "বেগ ভিজন AI",
    soundscape: "বতৰৰ শব্দ",
    popular: "প্ৰধান চহৰ:",
    gps: "জিপিএছ",
    searchPlaceholder: "চহৰ বিচাৰক (যেনে গুৱাহাটী, ডিব্ৰুগড়)...",
  },
  Urdu: {
    missionMode: "موسم مشن موڈ",
    radarMap: "لائیو بارش راڈار",
    emergencySOS: "ہنگامی امداد اور SOS",
    audioBulletin: "روزانہ موسمی بلیٹن",
    citizenPulse: "شہری رپورٹس",
    routeCorridor: "راستہ کوریڈور",
    disasterRadar: "آفت راڈار",
    sandbox: "موسمی سمیلیٹر",
    weatherDNA: "موسمی ڈی این اے",
    departure: "روانگی چیک لسٹ",
    askAI: "موسم وانی AI سے پوچھیں",
    bagVisionAI: "بیگ وژن AI",
    soundscape: "موسم کی آواز",
    popular: "اہم شہر:",
    gps: "جی پی ایس",
    searchPlaceholder: "شہر تلاش کریں (جیسے دہلی، لکھنؤ، حیدرآباد)...",
  },
};

export function getUITranslation(key: keyof UITranslationMap, languageName: string): string {
  const langConfig = getLanguage(languageName);
  const translations = UI_TRANSLATIONS[langConfig.name] || UI_TRANSLATIONS["English"];
  const defaultTranslations = UI_TRANSLATIONS["English"]!;
  return translations[key] || defaultTranslations[key] || String(key);
}
